services:
  frontend:
    build:
      context: ./Frontend/puppy-clicker
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend/puppy-clicker:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - puppy-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=puppypassword
      - DB_NAME=mydb
    networks:
      - puppy-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: puppypassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: puppypassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Backend/sql:/docker-entrypoint-initdb.d
    networks:
      - puppy-network

volumes:
  mysql_data:
    driver: local

networks:
  puppy-network:
    driver: bridge
